// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.panels;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class PanelHeaderBsResponsiveTag extends RichDeclarativeComponentTag {

  public PanelHeaderBsResponsiveTag() {
  }

  public String getComponentType() {
    return "skh.adf.custom.components.panels.PanelHeaderBsResponsiveComponentType";
  }

  protected String getViewId() {
    return "/components/bootstrap/panelheader/PanelHeaderBsResponsive.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new PanelHeaderBsResponsiveComponent();
  }

  public void setTitle(ValueExpression title) {
    this._title = title;
  }

  public void setCustomClass(ValueExpression customClass) {
    this._customClass = customClass;
  }

  public void setFaIcon(ValueExpression faIcon) {
    this._faIcon = faIcon;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_title != null)
      bean.setValueExpression(_TITLE_KEY, _title);
    if (_customClass != null)
      bean.setValueExpression(_CUSTOMCLASS_KEY, _customClass);
    if (_faIcon != null)
      bean.setValueExpression(_FAICON_KEY, _faIcon);
  }

  public void release() {
    super.release();
    _title = null;
    _customClass = null;
    _faIcon = null;
  }

  private ValueExpression _title;
  private ValueExpression _customClass;
  private ValueExpression _faIcon;

  private static final PropertyKey _TITLE_KEY = PropertyKey.createPropertyKey("title");
  private static final PropertyKey _CUSTOMCLASS_KEY = PropertyKey.createPropertyKey("customClass");
  private static final PropertyKey _FAICON_KEY = PropertyKey.createPropertyKey("faIcon");

}
