// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.panels;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class PanelHeaderInlineTitleTag extends RichDeclarativeComponentTag {

  public PanelHeaderInlineTitleTag() {
  }

  public String getComponentType() {
    return "skh.adf.custom.components.panels.PanelHeaderInlineTitleComponentType";
  }

  protected String getViewId() {
    return "/components/faces/panelheader/PanelHeaderInlineTitle.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new PanelHeaderInlineTitleComponent();
  }

  public void setTitle(ValueExpression title) {
    this._title = title;
  }

  public void setCustomClass(ValueExpression customClass) {
    this._customClass = customClass;
  }

  public void setFwClass(ValueExpression fwClass) {
    this._fwClass = fwClass;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_title != null)
      bean.setValueExpression(_TITLE_KEY, _title);
    if (_customClass != null)
      bean.setValueExpression(_CUSTOMCLASS_KEY, _customClass);
    if (_fwClass != null)
      bean.setValueExpression(_FWCLASS_KEY, _fwClass);
  }

  public void release() {
    super.release();
    _title = null;
    _customClass = null;
    _fwClass = null;
  }

  private ValueExpression _title;
  private ValueExpression _customClass;
  private ValueExpression _fwClass;

  private static final PropertyKey _TITLE_KEY = PropertyKey.createPropertyKey("title");
  private static final PropertyKey _CUSTOMCLASS_KEY = PropertyKey.createPropertyKey("customClass");
  private static final PropertyKey _FWCLASS_KEY = PropertyKey.createPropertyKey("fwClass");

}
