// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.panels;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class PanelHeaderInlineTitleComponent extends RichDeclarativeComponent {

  public PanelHeaderInlineTitleComponent() {
  }

  public String getTitle() {
    return (String) getAttributes().get("title");
  }

  public String getCustomClass() {
    return (String) getAttributes().get("customClass");
  }

  public String getFwClass() {
    return (String) getAttributes().get("fwClass");
  }



}
