// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.selections;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class RadioButtonCardComponent extends RichDeclarativeComponent {

  public RadioButtonCardComponent() {
  }

  public String getAttrBinding() {
    return (String) getAttributes().get("attrBinding");
  }

  public String getCustomClass() {
    return (String) getAttributes().get("customClass");
  }

  public String getLayout() {
    return (String) getAttributes().get("layout");
  }

  public Boolean getAutoSubmit() {
    return (Boolean) getAttributes().get("autoSubmit");
  }

  public Boolean getDisabled() {
    return (Boolean) getAttributes().get("disabled");
  }

  public String getLabel() {
    return (String) getAttributes().get("label");
  }



}
