// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class PanelHeaderBsResponsiveComponent extends RichDeclarativeComponent {

  public PanelHeaderBsResponsiveComponent() {
  }

  public String getTitle() {
    return (String) getAttributes().get("title");
  }

  public String getCustomClass() {
    return (String) getAttributes().get("customClass");
  }



}
