// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.html;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class BpmHistoryTrackerComponent extends RichDeclarativeComponent {

  public BpmHistoryTrackerComponent() {
  }

  public String getCustomClass() {
    return (String) getAttributes().get("customClass");
  }

  public String getBindingIter() {
    return (String) getAttributes().get("bindingIter");
  }



}
