// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.html;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class BpmHistoryTrackerTag extends RichDeclarativeComponentTag {

  public BpmHistoryTrackerTag() {
  }

  public String getComponentType() {
    return "skh.adf.custom.components.html.BpmHistoryTrackerComponentType";
  }

  protected String getViewId() {
    return "/components/html/BPMHistoryTracker.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new BpmHistoryTrackerComponent();
  }

  public void setCustomClass(ValueExpression customClass) {
    this._customClass = customClass;
  }

  public void setBindingIter(ValueExpression bindingIter) {
    this._bindingIter = bindingIter;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_customClass != null)
      bean.setValueExpression(_CUSTOMCLASS_KEY, _customClass);
    if (_bindingIter != null)
      bean.setValueExpression(_BINDINGITER_KEY, _bindingIter);
  }

  public void release() {
    super.release();
    _customClass = null;
    _bindingIter = null;
  }

  private ValueExpression _customClass;
  private ValueExpression _bindingIter;

  private static final PropertyKey _CUSTOMCLASS_KEY = PropertyKey.createPropertyKey("customClass");
  private static final PropertyKey _BINDINGITER_KEY = PropertyKey.createPropertyKey("bindingIter");

}
