// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.html;

import skh.adf.custom.components.html.VerticalTracker;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class VerticalTrackerComponent extends VerticalTracker {

  public VerticalTrackerComponent() {
  }

  public String getIterName() {
    return (String) getAttributes().get("iterName");
  }

  public String getCustomClass() {
    return (String) getAttributes().get("customClass");
  }

  public String getTitleAttrName() {
    return (String) getAttributes().get("titleAttrName");
  }

  public String getTitleClass() {
    return (String) getAttributes().get("titleClass");
  }

  public String getSubTitleAttrName() {
    return (String) getAttributes().get("subTitleAttrName");
  }

  public String getSubTitleClass() {
    return (String) getAttributes().get("subTitleClass");
  }

  public String getCircularAttrName() {
    return (String) getAttributes().get("circularAttrName");
  }

  public String getCircularClass() {
    return (String) getAttributes().get("circularClass");
  }

  public java.util.ArrayList getFlatDataAttrsNames() {
    return (java.util.ArrayList) getAttributes().get("flatDataAttrsNames");
  }



}
