// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package skh.adf.custom.components.selections;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class RadioButtonCardTag extends RichDeclarativeComponentTag {

  public RadioButtonCardTag() {
  }

  public String getComponentType() {
    return "skh.adf.custom.components.selections.RadioButtonCardComponentType";
  }

  protected String getViewId() {
    return "/components/faces/radiobuttons/RadioButtonCard.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new RadioButtonCardComponent();
  }

  public void setAttrBinding(ValueExpression attrBinding) {
    this._attrBinding = attrBinding;
  }

  public void setCustomClass(ValueExpression customClass) {
    this._customClass = customClass;
  }

  public void setLayout(ValueExpression layout) {
    this._layout = layout;
  }

  public void setAutoSubmit(ValueExpression autoSubmit) {
    this._autoSubmit = autoSubmit;
  }

  public void setDisabled(ValueExpression disabled) {
    this._disabled = disabled;
  }

  public void setLabel(ValueExpression label) {
    this._label = label;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_attrBinding != null)
      bean.setValueExpression(_ATTRBINDING_KEY, _attrBinding);
    if (_customClass != null)
      bean.setValueExpression(_CUSTOMCLASS_KEY, _customClass);
    if (_layout != null)
      bean.setValueExpression(_LAYOUT_KEY, _layout);
    if (_autoSubmit != null)
      bean.setValueExpression(_AUTOSUBMIT_KEY, _autoSubmit);
    if (_disabled != null)
      bean.setValueExpression(_DISABLED_KEY, _disabled);
    if (_label != null)
      bean.setValueExpression(_LABEL_KEY, _label);
  }

  public void release() {
    super.release();
    _attrBinding = null;
    _customClass = null;
    _layout = null;
    _autoSubmit = null;
    _disabled = null;
    _label = null;
  }

  private ValueExpression _attrBinding;
  private ValueExpression _customClass;
  private ValueExpression _layout;
  private ValueExpression _autoSubmit;
  private ValueExpression _disabled;
  private ValueExpression _label;

  private static final PropertyKey _ATTRBINDING_KEY = PropertyKey.createPropertyKey("attrBinding");
  private static final PropertyKey _CUSTOMCLASS_KEY = PropertyKey.createPropertyKey("customClass");
  private static final PropertyKey _LAYOUT_KEY = PropertyKey.createPropertyKey("layout");
  private static final PropertyKey _AUTOSUBMIT_KEY = PropertyKey.createPropertyKey("autoSubmit");
  private static final PropertyKey _DISABLED_KEY = PropertyKey.createPropertyKey("disabled");
  private static final PropertyKey _LABEL_KEY = PropertyKey.createPropertyKey("label");

}
